title: Rifqi Hafizuddin
logo:  assets/img/カウントダウン_④.png
description: Hello! My name is Rifqi. I'm an undergraduate statistics student at Universitas Indonesia. 
#show_downloads: true
theme: jekyll-theme-minimal
